# Use the production image as base image
FROM node-docker
# Copy the test files
COPY tests tests
# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev
# 1. Get test packages; AND
# 2. Install our test framework - mocha
RUN npm install && \
    npm install -g tape
# Override the command, to run the test instead of the application
CMD ["tape", "tests/app.js"]

# build with
# docker build -t node-docker-test -f Dockerfile.test .

# run with
# docker run --rm node-docker-test